extends SceneTree

func _init() -> void:
	var game := GameManager.new()
	assert(not game.is_fire_active("campfire"))
	game.resources.amounts["wood"] = 0
	var no_wood: Dictionary = game.add_fire_fuel("campfire", 1)
	assert(not bool(no_wood.get("ok", false)))
	game.resources.add("wood", 2)
	var lit: Dictionary = game.add_fire_fuel("campfire", 1)
	assert(bool(lit.get("ok", false)))
	assert(game.resources.get_amount("wood") == 1)
	assert(game.is_fire_active("campfire"))
	var remaining := float(game.fire_state("campfire").get("fuel_remaining", 0.0))
	var topped_up: Dictionary = game.add_fire_fuel("campfire", 1)
	assert(bool(topped_up.get("ok", false)))
	assert(game.resources.get_amount("wood") == 0)
	assert(is_equal_approx(float(game.fire_state("campfire").get("fuel_remaining", 0.0)), 240.0))
	game.resources.add("wood", 2)
	var filled: Dictionary = game.add_fire_fuel("campfire", 1)
	assert(bool(filled.get("ok", false)))
	assert(is_equal_approx(float(game.fire_state("campfire").get("fuel_remaining", 0.0)), 360.0))
	var full: Dictionary = game.add_fire_fuel("campfire", 1)
	assert(not bool(full.get("ok", false)))
	var compatibility := GameManager.new()
	compatibility.resources.amounts["wood"] = 2
	compatibility.house_fire_lit = true
	assert(compatibility.resources.get_amount("wood") == 2)
	assert(float(compatibility.fire_state("house_fireplace").get("fuel_remaining", 0.0)) == 0.0)
	assert(not compatibility.house_fire_lit)
	assert(not compatibility.is_fire_active("house_fireplace"))
	compatibility.resources.add("wood", 1)
	assert(bool(compatibility.add_fire_fuel("house_fireplace", 1).get("ok", false)))
	compatibility.house_fire_lit = false
	assert(float(compatibility.fire_state("house_fireplace").get("fuel_remaining", 0.0)) == 0.0)
	assert(not compatibility.house_fire_lit)
	compatibility.house_fire_lit = true
	assert(not compatibility.house_fire_lit)
	assert(not compatibility.is_fire_active("house_fireplace"))
	var legacy_save: Dictionary = compatibility.to_dict()
	legacy_save.erase("fire_states")
	legacy_save["house_fire_lit"] = true
	var migrated := GameManager.new()
	migrated.from_dict(legacy_save)
	assert(migrated.is_fire_active("house_fireplace"))
	assert(is_equal_approx(float(migrated.fire_state("house_fireplace").get("fuel_remaining", 0.0)), 120.0))
	assert(migrated.daily_log.back().contains("旧存档兼容"))
	game.tick_fire(remaining + 0.1)
	assert(game.is_fire_active("campfire"))
	game.tick_fire(1000.0)
	assert(not game.is_fire_active("campfire"))
	var cold_temperature := game.get_environment_temperature()
	game.outdoor_position = Vector2(210, 153)
	assert(game.get_environment_temperature() == cold_temperature + 0.0)
	var fireplace := FireplacePoint.new()
	root.add_child(fireplace)
	fireplace.setup(game)
	game.resources.add("wood", 1)
	var house_lit: Dictionary = game.add_fire_fuel("house_fireplace", 1)
	assert(bool(house_lit.get("ok", false)))
	game.resources.add("wood", 2)
	var house_topup: Dictionary = game.add_fire_fuel("house_fireplace", 2)
	assert(bool(house_topup.get("ok", false)))
	assert(not fireplace.can_interact())
	assert(fireplace.prompt_text().contains("满"))
	print("CAMPFIRE_FUEL_REGRESSION_OK")
	quit()
