extends SceneTree

const ResourceCatalog = preload("res://scripts/domain/inventory/resource_catalog.gd")
const ResourceLedger = preload("res://scripts/domain/inventory/resource_ledger.gd")
const InventoryState = preload("res://scripts/domain/inventory/inventory_state.gd")

func _init() -> void:
	var catalog := ResourceCatalog.new()
	assert("fish_carp" in catalog.item_keys())
	assert(catalog.display_name("wood") != "wood")
	assert(catalog.INITIAL_AMOUNTS["food"] == 12)
	assert(catalog.CAPACITIES["wood"] == 35)
	assert(catalog.display_name("axe") == "石斧")
	var ledger := ResourceLedger.new(catalog)
	assert(ledger.can_afford({"wood": 1}))
	var before := ledger.get_amount("wood")
	assert(ledger.spend({"wood": 1}))
	assert(ledger.get_amount("wood") == before - 1)
	var reward_before := ledger.get_amount("wood")
	var blocked := ledger.collect_rewards_atomic({"wood": 9999, "stone": 1}, "field_branch")
	assert(not bool(blocked.get("ok", false)))
	assert(not bool(blocked.get("changed", true)))
	assert(ledger.get_amount("wood") == reward_before)
	var inventory := InventoryState.new(catalog)
	inventory.backpack["wood"] = 1
	assert(inventory.backpack_slots_used() == 1)
	assert(inventory.move_to_storage("wood", 1)["ok"])
	assert(inventory.backpack.get("wood", 0) == 0)
	assert(inventory.storage.get("wood", 0) == 1)
	inventory.backpack_capacity = 1
	inventory.backpack["stone"] = 1
	inventory.storage["medicine"] = 1
	var slots_before := inventory.backpack_slots_used()
	var full := inventory.move_to_backpack("medicine", 1)
	assert(not bool(full.get("ok", false)))
	assert(inventory.backpack_slots_used() == slots_before)
	assert(inventory.storage.get("medicine", 0) == 1)
	var bound := InventoryState.new(catalog)
	var bound_ledger := ResourceLedger.new(catalog, bound)
	var collected := bound_ledger.collect_rewards_atomic({"fish_carp": 1}, "fishing_spot")
	assert(bool(collected.get("ok", false)))
	assert(bound.backpack["fish_carp"] == 1)
	bound.backpack_capacity = 1
	bound.backpack["wood"] = 1
	var bound_blocked := bound_ledger.collect_rewards_atomic({"medicine": 1, "metal": 1}, "field_branch")
	assert(not bool(bound_blocked.get("ok", false)))
	assert(bound.backpack.get("medicine", 0) == 0)
	var camp := bound_ledger.collect_rewards_atomic({"wood": 1}, "camp_task")
	assert(bool(camp.get("ok", false)))
	assert(camp.get("reason", "") == "奖励已存入营地。")
	var restored := InventoryState.new(catalog)
	restored.from_dict({"backpack": "bad", "storage": 4, "amounts": {"food": 8, "cooked_food": 4}, "backpack_capacity": 2})
	assert(restored.backpack_capacity == 12)
	assert(restored.storage["food"] == 8)
	assert(restored.storage["cooked_food"] == 0)
	var sync_inventory := InventoryState.new(catalog)
	var sync_ledger := ResourceLedger.new(catalog, sync_inventory)
	var storage_before := sync_ledger.get_amount("wood")
	assert(sync_ledger.add("wood", 2) == 2)
	assert(sync_ledger.get_amount("wood") == storage_before + 2)
	assert(sync_inventory.storage["wood"] == 2)
	assert(sync_ledger.spend({"wood": 1}))
	assert(sync_ledger.get_amount("wood") == storage_before + 1)
	assert(sync_inventory.storage["wood"] == 1)
	var backpack_reward := sync_ledger.collect_rewards_atomic({"fish_carp": 1}, "fishing_spot")
	assert(bool(backpack_reward.get("ok", false)))
	assert(sync_inventory.backpack["fish_carp"] == 1)
	assert(sync_inventory.storage["fish_carp"] == 0)
	var camp_reward := sync_ledger.collect_rewards_atomic({"fish_bass": 1}, "camp_task")
	assert(bool(camp_reward.get("ok", false)))
	assert(sync_inventory.storage["fish_bass"] == 1)
	assert(sync_inventory.backpack["fish_bass"] == 0)
	print("INVENTORY_DOMAIN_REGRESSION_OK")
	quit()
