extends SceneTree

const UiFactory = preload("res://scripts/presentation/theme/ui_factory.gd")

func _init() -> void:
	var host := Control.new()
	root.add_child(host)
	var factory := UiFactory.new()
	factory.setup(null)
	assert(factory.theme != null)
	assert(factory.theme.default_font == PixelUITheme.FONT)
	assert(factory.theme.default_font_size == PixelUITheme.FONT_SIZE_BODY)
	var fusion_font := PixelUITheme.FONT as FontFile
	assert(fusion_font != null)
	assert(fusion_font.antialiasing == TextServer.FONT_ANTIALIASING_NONE)
	assert(fusion_font.hinting == TextServer.HINTING_NONE)
	assert(fusion_font.subpixel_positioning == TextServer.SUBPIXEL_POSITIONING_DISABLED)
	var panel := factory.panel(host, Vector2(12, 12), Vector2(120, 30), Color.WHITE)
	var label := factory.label(host, Vector2(15, 15), Vector2(80, 12), "测试", 10, Color.WHITE)
	var button := factory.button(host, Vector2(18, 48), Vector2(96, 30), "确认")
	var icon := factory.icon(host, Vector2(24, 84), Vector2(16, 16), PixelUITheme.PANEL_TEXTURE)
	var progress := factory.progress_bar(host, Vector2(12, 108), Vector2(120, 6), Color("70a9a0"))
	assert(panel.position == Vector2(12, 12))
	assert(panel.size == Vector2(120, 30))
	assert(panel.scale == Vector2.ONE)
	assert(label.position == Vector2(15, 15))
	assert(label.size.x == 80)
	assert(label.size.y >= 12)
	assert(button.position == Vector2(18, 48))
	assert(button.size == Vector2(96, 30))
	_assert_button_style(button, "normal", Color("1c3032"), PixelUITheme.PANEL_TEXTURE)
	_assert_button_style(button, "hover", Color("2c4a49"), PixelUITheme.PANEL_INLAY_TEXTURE)
	_assert_button_style(button, "pressed", Color("152527"), PixelUITheme.PANEL_INLAY_TEXTURE)
	_assert_button_style(button, "disabled", Color("182325", 0.8), PixelUITheme.DISABLED_TEXTURE)
	_assert_button_style(button, "focus", Color("3a534d"), PixelUITheme.PANEL_INLAY_TEXTURE)
	assert(icon.texture == PixelUITheme.PANEL_TEXTURE)
	assert(icon.texture_filter == CanvasItem.TEXTURE_FILTER_NEAREST)
	assert(progress.position == Vector2(12, 108))
	assert(progress.size.x >= 120)
	assert(progress.size.y >= 6)
	assert(progress.get_theme_stylebox("background") is StyleBoxTexture)
	assert(progress.get_theme_stylebox("fill") is StyleBoxTexture)
	print("UI_FACTORY_REGRESSION_OK")
	quit()

func _assert_button_style(button: Button, state: StringName, tint: Color, texture: Texture2D) -> void:
	var actual := button.get_theme_stylebox(state)
	assert(actual is StyleBoxTexture, str(state))
	var expected := PixelUITheme.button_style(tint, texture)
	assert((actual as StyleBoxTexture).texture == expected.texture, str(state))
	assert((actual as StyleBoxTexture).modulate_color == expected.modulate_color, str(state))
	assert((actual as StyleBoxTexture).texture_margin_left == expected.texture_margin_left, str(state))
	assert((actual as StyleBoxTexture).content_margin_left == expected.content_margin_left, str(state))
