extends SceneTree

const UiFactory = preload("res://scripts/presentation/theme/ui_factory.gd")

func _init() -> void:
	var host := Control.new()
	root.add_child(host)
	var factory := UiFactory.new()
	factory.setup(null)
	var panel := factory.panel(host, Vector2(12, 12), Vector2(120, 30), Color.WHITE)
	var label := factory.label(host, Vector2(15, 15), Vector2(80, 12), "测试", 10, Color.WHITE)
	var button := factory.button(host, Vector2(18, 48), Vector2(96, 30), "确认")
	var icon := factory.icon(host, Vector2(24, 84), Vector2(16, 16), PixelUITheme.PANEL_TEXTURE)
	var progress := factory.progress_bar(host, Vector2(12, 108), Vector2(120, 6), Color("70a9a0"))
	assert(panel.position == Vector2(12, 12))
	assert(panel.size == Vector2(120, 30))
	assert(panel.scale == Vector2.ONE)
	assert(label.position == Vector2(15, 15))
	assert(label.size.x == 80)
	assert(label.size.y >= 12)
	assert(button.position == Vector2(18, 48))
	assert(button.size == Vector2(96, 30))
	assert(icon.texture == PixelUITheme.PANEL_TEXTURE)
	assert(icon.texture_filter == CanvasItem.TEXTURE_FILTER_NEAREST)
	assert(progress.position == Vector2(12, 108))
	assert(progress.size.x >= 120)
	assert(progress.size.y >= 6)
	assert(progress.get_theme_stylebox("background") is StyleBoxTexture)
	assert(progress.get_theme_stylebox("fill") is StyleBoxTexture)
	print("UI_FACTORY_REGRESSION_OK")
	quit()
